### ISSUE TITLE
first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by akbarali1** [ClickHouse/clickhouse-go#1176]
### Steps to reproduce
1. I have hosted Clickhouse on docker.
2. I get an error when I try to connect to Clickhouse. 
`first record does not look like a TLS handshake`

### Code example
```go
func ClickHouseConn() driver.Conn {
	errLoad := godotenv.Load(".env")
	if errLoad != nil {
		log.Fatal("Error loading .env file")
	}

	var (
		ctx            = context.Background()
		clickHouseUser = os.Getenv("CLICKHOUSE_USER")
		clickHousePass = os.Getenv("CLICKHOUSE_PASSWORD")
		clickHouseHost = os.Getenv("CLICKHOUSE_HOST")
		clickHouseDb   = os.Getenv("CLICKHOUSE_DATABASE")
		clickHousePort = os.Getenv("CLICKHOUSE_PORT")
		connect        = fmt.Sprintf("%s:%s", clickHouseHost, clickHousePort)

		conn, err = clickhouse.Open(&clickhouse.Options{
			Addr: []string{connect},
			Auth: clickhouse.Auth{
				Database: clickHouseDb,
				Username: clickHouseUser,
				Password: clickHousePass,
			},
			ClientInfo: clickhouse.ClientInfo{
				Products: []struct {
					Name    string
					Version string
				}{
					{Name: "an-example-go-client", Version: "0.1"},
				},
			},

			Debugf: func(format string, v ...interface{}) {
				fmt.Printf(format, v)
			},
			TLS: &tls.Config{
				InsecureSkipVerify: true,
			},
		})
	)

	if err != nil {
		panic(err)
	}

	if err := conn.Ping(ctx); err != nil {
		var exception *clickhouse.Exception
		if errors.As(err, &exception) {
			log.Fatalf("Exception [%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		}
		panic(err)
	}
	return conn
}

```
### Error log
`first record does not look like a TLS handshake`

### Configuration
Docker:
```
version: '3'

services:
  click_server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./dbfiles:/var/lib/clickhouse
      - ./config/houseadmin.xml:/etc/clickhouse-server/users.d/houseadmin.xml

  click_client:
    image: clickhouse/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
```
#### Environment
* Client version: 
* Language version:
* OS:
* Interface: ClickHouse API / database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version: ClickHouse server version 23.12.2.

**Comment by Slach** [comment]
try to use 9000 port instead of 8123

**Comment by jkaflik** [comment]
@Slach already provided a brief instruction on what should be done.

@akbarali1 `8123` is a HTTP port without TLS. At the same time your `clickhouse.Options` forces to use native (TCP) protocol with TLS enabled. Either expose `9000` from container and use it without TLS or change to HTTP without TLS.

**Comment by akbarali1** [comment]
> try to use 9000 port instead of 8123 and remove
> 
> ```
> TLS: &tls.Config{
>  InsecureSkipVerify: true,
> },
> ```
> 
> you try to TLS connect for 8123 port, this is imposible
> 
> TLS connection for 9440 port and need `tcp_secure` in clickhouse-server settings

I'm running through clickhouse docker. So how do I set it up?

**Comment by Slach** [comment]
better use 9000 if you can't config SSL properly

briefly
*tcp_secure.xml*
```xml
<clickhouse><tcp_secure>9440</tcp_secure></clickhouse>
```

*docker-compose.yaml*
```yaml
volumes:
 - ./tcp_secure.xml:/etc/clickhouse-server/config.d/tcp_secure.xml
```

**Comment by akbarali1** [comment]
Thanks everyone, I solved this problem by changing `docker-compose.yml` like this
```
version: '3'

services:
  click_server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "8124:9000"
    volumes:
      - ./dbfiles:/var/lib/clickhouse
      - ./config/houseadmin.xml:/etc/clickhouse-server/users.d/houseadmin.xml

  click_client:
    image: clickhouse/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
```
